language: python
python:
  - '3.8'

before_script:
  - pipenv install
  - export MOZ_HEADLESS=1

after_script:
  - unset MOZ_HEADLESS

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings.travis"

services:
  - postgresql

branches:
  only:
    - staging

script:
  - ./manage.py test catalogue/tests/ user/tests/
