language: python
python:
  - '3.8'

before_script:
  - pipenv install

env: DJANGO_SETTINGS_MODULE="PurBeurre.settings.travis"

services:
  - postgresql

# safelist
branches:
  only:
    - staging

script:
  - ./manage.py test catalogue/tests/ user/tests/
